GET http://localhost:3000/

###

GET http://localhost:3000/bye

###

GET http://localhost:3000/login

###
POST http://localhost:3000/
Content-Type: application/json

{
    "name": "ZT"
}

###

POST http://localhost:3000/login2
Content-Type: application/json

{
    "username": "lee",
    "password": "passwordlee"
}