GET http://localhost:3000/

###

GET http://localhost:3000/bye

###

GET http://localhost:3000/login

###
POST http://localhost:3000/
Content-Type: application/json

{
    "name": "ZT"
}

###

POST http://localhost:3000/login2
Content-Type: application/json

{
    "username": "lee",
    "password": "passwordlee"
}

###

POST http://localhost:3000/register
Content-Type: application/json

{
    //should be same as the res.send(register...'s name of the var) -- line 124 in index.js
    "regusername": "leee",
    "regpassword": "passwordlee",
    "regname": "lee zhao tian",
    "regemail" :"lzt@gmail.com"
}